version: '3'

services:

  app:
    build: .
    working_dir: /opt/app
    volumes:
      - .:/opt/app
    environment:
      SKIP_PHOENIX: "true"
      # dev or test
      MIX_ENV: "dev"
    depends_on:
      - db
    ports:
      - 4000:4000

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rocketpay_dev
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432

volumes:
  rocketpay: