version: '3'

services:

  # mongo:
  #   image: mongo
  #   restart: always
  #   # environment:
  #     # MONGO_INITDB_ROOT_USERNAME: root
  #     # MONGO_INITDB_ROOT_PASSWORD: example
  #   ports:
  #     - 27017:27017

  postgres:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rocketpay_dev
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432

  # redis:
  #   image: redis:alpine
  #   ports:
  #     - 6379:6379